### ISSUE TITLE
2.3 Creating a configuration for prescribing rights for each role

### ISSUE THREAD

**Issue by Lion6477** [Team-Maksym/backend#1]
- [x] Create a SecurityConfiguration for the rights of each role.
- [x] Configure SecurityConfiguration for skipping accounts to the given link ("/talents/{talentId}"), only if you have the TALENT role, by going to which it will be possible to view full information about talent.

More details in [file](https://docs.google.com/document/d/16IbxNAmdyyxDkB025VjU5otUvbZas1fy7INFZ6qkzng/edit?usp=sharing)

**Comment by KateySt** [comment]
[2. As a talent I want to be able to view the personal profile of another talent for reference](https://github.com/Team-Maksym/.github/issues/2)
